# Generated by Django 3.0.3 on 2020-02-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorization',
            field=models.IntegerField(default=1),
        ),
    ]
