# Generated by Django 3.0.3 on 2020-02-13 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_authorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='healthyCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=6)),
                ('condition', models.CharField(max_length=20)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('date', models.DateField(auto_now_add=True)),
                ('position', models.CharField(max_length=40)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
