# Generated by Django 3.0.3 on 2020-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_healthycondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男 ', max_length=6),
            preserve_default=False,
        ),
    ]
