# Generated by Django 3.0.3 on 2020-02-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthycondition',
            name='sex',
        ),
    ]
